name: Run Hardhat Test

on: [push]

jobs:
    test_hardhat:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v3
        with:
            node-version: 16
        - name: NPM Clean Install
        run: npm ci
        - name: Run All Hardhat Tests
        run: npx hardhat test
        - name: Run hardhat coverage on all Test
        run: npx hardhat coverage